# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68e7be4ce9b7bc0132d7156bbcd42ba6e181e6e996dfcded08d7c3f9e6863efd712f697282bff4a670e6b0b33168433fb6381ffca2fa9a484f2590f4d5457689

test:
  secret_key_base: e957114afd24ffb0777e91ab6992d9099c59a7022d6ab405bfbe9fc19e597c329c600a214d4b659d43e48d958f34379fa99bbb94340607f5c63126ef74cb6331

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
